image: maven:3.9.5-eclipse-temurin-17

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  MAVEN_CLI_OPTS: "-B -e -V"
  GIT_DEPTH: 0  # Ensure complete history for versioning if needed

cache:
  paths:
    - .m2/repository
    - target/

stages:
  - build
  - test
  - report

before_script:
  - echo "Using Maven version: $(mvn -v | head -n 1)"

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean compile
  artifacts:
    paths:
      - target/

unit_tests:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test
  artifacts:
    reports:
      junit: target/surefire-reports/*.xml
    paths:
      - target/jacoco-ut.exec
      - target/surefire-reports/
    when: always

integration_tests:
  stage: test
  services:
    - name: docker:dind
      alias: docker
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_TLS_CERTDIR: ""
  script:
    - mvn $MAVEN_CLI_OPTS verify -Dskip.unit.tests=false
  artifacts:
    reports:
      junit: target/failsafe-reports/*.xml
    paths:
      - target/jacoco-it.exec
      - target/failsafe-reports/
    when: always

coverage_report:
  stage: report
  script:
    - mvn $MAVEN_CLI_OPTS jacoco:merge jacoco:report
  artifacts:
    paths:
      - target/site/jacoco/
    when: always
  only:
    - main
    - merge_requests
