image: maven:3.9.5-eclipse-temurin-17

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_TLS_CERTDIR: ""

stages:
  - build
  - test
  - report

before_script:
  - echo "Using Maven version:"
  - mvn -v | head -n 1

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean compile
  artifacts:
    paths:
      - target/

unit_tests:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test
  artifacts:
    paths:
      - target/jacoco-ut.exec
      - target/surefire-reports/
    when: always

integration_tests:
  stage: test
  services:
    - name: docker:dind
      alias: docker
  script:
    - mvn $MAVEN_CLI_OPTS verify
  artifacts:
    paths:
      - target/jacoco-it.exec
      - target/failsafe-reports/
    when: always

coverage_report:
  stage: report
  dependencies:
    - unit_tests
    - integration_tests
  script:
    - mvn $MAVEN_CLI_OPTS jacoco:merge jacoco:report
  artifacts:
    paths:
      - target/site/jacoco/
    when: always
  only:
    - main
    - merge_requests