# .gitlab-ci.yml
image: maven:3.8.7-eclipse-temurin-17

services:
  - postgres:14

variables:
  POSTGRES_DB: testdb
  POSTGRES_USER: testuser
  POSTGRES_PASSWORD: testpass

stages:
  - test

before_script:
  - export SPRING_DATASOURCE_URL="jdbc:postgresql://postgres:5432/$POSTGRES_DB"
  - export SPRING_DATASOURCE_USERNAME=$POSTGRES_USER
  - export SPRING_DATASOURCE_PASSWORD=$POSTGRES_PASSWORD

test:
  stage: test
  script:
    - mvn clean test


 image: docker:24.0.2

services:
  - docker:24.0.2-dind

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_TLS_CERTDIR: ""
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

stages:
  - test

test:
  stage: test
  image: maven:3.9.4-eclipse-temurin-17
  services:
    - docker:24.0.2-dind
  script:
    - echo "Running tests..."
    - mvn clean test
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - .m2/repository
   
