# .gitlab-ci.yml

image: maven:3.9.4-eclipse-temurin-17

services:
  - docker:24.0.2-dind
  - postgres:14

variables:
  POSTGRES_DB: testdb
  POSTGRES_USER: testuser
  POSTGRES_PASSWORD: testpass
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_TLS_CERTDIR: ""
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/testdb"
  SPRING_DATASOURCE_USERNAME: "testuser"
  SPRING_DATASOURCE_PASSWORD: "testpass"

stages:
  - test

test:
  stage: test
  script:
    - echo "Running tests with coverage..."
    - mvn clean verify
  coverage: '/Total.*?([0-9]{1,3})%/'
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - .m2/repository
