image: maven:3.9.5-eclipse-temurin-17

services:
  - name: docker:24.0.2-dind
    alias: docker

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_TLS_CERTDIR: ""
  MAVEN_CLI_OPTS: "-B -Dmaven.repo.local=.m2/repository"

stages:
  - build
  - test
  - report

cache:
  paths:
    - .m2/repository

before_script:
  - apt-get update && apt-get install -y docker.io  # Ensures Docker CLI is available
  - docker info || echo "Docker not available"

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean compile
  artifacts:
    paths:
      - target/

unit_tests:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test -Djacoco.destFile=target/jacoco-ut.exec
  artifacts:
    paths:
      - target/jacoco-ut.exec
      - target/surefire-reports/
    when: always

integration_tests:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS verify -Djacoco.destFile=target/jacoco-it.exec
  artifacts:
    paths:
      - target/jacoco-it.exec
      - target/failsafe-reports/
    when: always

coverage_report:
  stage: report
  dependencies:
    - unit_tests
    - integration_tests
  script:
  - mvn $MAVEN_CLI_OPTS jacoco:merge
  - mvn $MAVEN_CLI_OPTS jacoco:report -Djacoco.dataFile=target/jacoco-merged.exec

  artifacts:
    paths:
      - target/site/jacoco/
    when: always
  only:
    - main
    - merge_requests
