version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: qalab-postgres
    environment:
      POSTGRES_USER: qalab
      POSTGRES_PASSWORD: qalab123
      POSTGRES_DB: bugtracker
    ports:
      - "5433:5432"
    networks:
      - qalab-network
  backend:
    image: bugtracker
    container_name: bugtracker-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://qalab-postgres:5432/bugtracker
      SPRING_DATASOURCE_USERNAME: qalab
      SPRING_DATASOURCE_PASSWORD: qalab123
    networks:
      - qalab-network

networks:
  qalab-network:
    driver: bridge
